version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:7.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install --no-progress
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running tests
          command: |
            sudo npm test -- --single-run --no-progress -cc
            sudo npm run coveralls
            sudo npm run bundlesize
